### ISSUE TITLE
Archivo splash

### ISSUE THREAD

**Issue by AdrianaEsvereidyTV** [AdrianaEsvereidyTV/Proyecto-5--Easy-Visit#14]
- [x] Generar la primera vista index.html pantalla inicial de la app
- [x] Redireccionar a la segunda vista de registro.html
- [x] Archivo css para dar el estilo al splash
- [x] Archivo js para la función de redireccionar
- [x] Siguiendo con el proceso de UX para la fidelidad de los alcances

**Comment by dianalopz** [comment]
La vista splash fue re-diseñada ya que al realizar las pruebas con usuarios finales, nos percatamos de que el fondo causaba mucho conflictos con el usuario final.
